window.onload = function() {
  document.body.append(titulo);
  document.body.append(preguntas);
  document.body.append(pregunta1);
  document.body.append(respuesta1de1);
  document.body.append(respuesta2de1);
  document.body.append(respuesta3de1);
  document.body.append(respuesta4de1);
  document.body.append(respuestasDe1);
  document.body.append(formulario);
  document.body.append(form);
  document.body.append(label);
  preguntas.appendChild(pregunta1);
  titulo.append(textoTitulo);
  pregunta1.append(texto1);
  pregunta1.appendChild(respuestasDe1);
  respuestasDe1.appendChild(respuesta1de1);
  respuesta1de1.append(texto2);
  formulario.appendChild(form);
  form.appendChild(label);
};


var titulo = document.createElement('h1');
var textoTitulo = document.createTextNode('Hola');
var formulario = document.createElement('div');
var form = document.createElement('form');
var label = document.createElement('label');
var preguntas = document.createElement('ul');
var pregunta1 = document.createElement('li');
var texto1 = document.createTextNode('Hola');
var respuestasDe1 = document.createElement('ul');
var respuesta1de1 = document.createElement('li');
var respuesta2de1 = document.createElement('li');
var respuesta3de1 = document.createElement('li');
var respuesta4de1 = document.createElement('li');
var texto1 = document.createTextNode('Hola');
var texto2 = document.createTextNode('Hola');
var texto3 = document.createTextNode('Hola');
var texto4 = document.createTextNode('Hola');
var texto5 = document.createTextNode('Hola');
var texto6 = document.createTextNode('Hola');
